[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  "F",   # pyflakes
  "E",   # pycodestyle
  "W",   # pycodestyle
  "I",   # isort
  "N",   # pep8-naming
  "B",   # flake8-ubgbear
  "ANN", # flake8-annotations
  "Q",   # flake8-quotes
  "PTH", # flake8-use-pathlib
  "UP",  # pyupgrade,
]

[tool.mypy]
