name: Python Ruff Lint and commit

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
    - name: Install Ruff
      run: pip install ruff

    - name: Ruff check and fix
      run: |
        ruff check .
        ruff fix .

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Python style fixes from Ruff'
